### ISSUE TITLE
Clarification on Leaderboard API Documentation

### ISSUE THREAD

**Issue by csmc88** [CrowdTangle/API#12]
Hi,

I was reading the parameters for the [Leaderboard API endpoint](https://github.com/CrowdTangle/API/wiki/Leaderboard) and I found the entry for `sortBy` confusing. 

The documented default value is `totalInteractionCount` while the possible values are `total_interactions` and `interaction_rate`. Could you clarify which is the correct value if we want to sort by the total amount of interactions?  For example, the [CrowdTangle API for posts](https://github.com/CrowdTangle/API/wiki/Posts) has more options on the `sortBy` parameter.

I'll be working with the API so I'm open to help find/correct these sort of details.

EDIT: 

Forgot to mention. The response from the leaderboard API contains `totalInteractionCount` whereas the posts API does not contain any field with a similar name

**Comment by mattynoce** [comment]
Hi, you caught a typo! The default value is total_interactions -- as you noted in your edit, we accidentally put in the return value instead of the parameter name.

The posts API has more options because some things make more sense for individual posts than they do for aggregations (e.g. overperforming).

Thanks for the note!

**Comment by csmc88** [comment]
Awesome! thanks @mattynoce
