### ISSUE TITLE
How is "expected" statistics calculated

### ISSUE THREAD

**Issue by systemaddict** [CrowdTangle/API#4]
> A set of key-values pairs representing the metrics CrowdTangle expected a post like this to accrue.

Can you explain how the "expected" statistics is calculated (or point me in a direction of some sort of explanation).

**Comment by tcmetzger** [comment]
Since this has been unanswered for a while now, I can try to answer this from my knowledge as a user of crowdtangle. The workings are explained in this FAQ: https://www.crowdtangle.com/resources/faq#metrics - so basically CT first determins what kind of post it is dealing with (status update, video, photo, etc.) and then compares this most recent post with the 100 past postings of the same kind (eg. a newly postet video gets compared with the 100 previous video's performance).

**Comment by mattynoce** [comment]
Hi, sorry for the delay, I completely missed this when it came in.

Timo's link is correct -- for every account, for every post type, for every age of the post, we pull the last 100, cut the top and the bottom to account for power law, and average what's left.

Eg for the CrowdTangle Page, if we post a video and it's 2 hours old, we'll compare it to a benchmark that looks at the last 100 CrowdTangle Page videos that were 2 hours old. 

I hope that helps!
